WAVE_BASE_ENEMY_COUNT = 20
WAVE_ENEMY_COUNT_INCREMENT = 3
INTERMISSION_DURATION_S = 3.0
WAVE_ANNOUNCEMENT_DURATION_S = 2.0
WAVE_PREP_DURATION_S = 1.0

WAVE_HUD_COLOR = (220, 220, 220)
WAVE_HUD_ENEMIES_COLOR = (255, 180, 80)
WAVE_HUD_MARGIN_X = 16
WAVE_HUD_MARGIN_Y = 12
WAVE_HUD_FONT_SIZE = 28
WAVE_HUD_GAP = 20

WAVE_ANNOUNCEMENT_COLOR = (255, 255, 255)
WAVE_ANNOUNCEMENT_FONT_SIZE = 96


def enemies_for_wave(wave_number: int) -> int:
    return WAVE_BASE_ENEMY_COUNT + (wave_number - 1) * WAVE_ENEMY_COUNT_INCREMENT
